# Generated by Django 4.1.3 on 2022-11-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='ew', upload_to='gallary'),
            preserve_default=False,
        ),
    ]
